---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: crdviz
  name: crdviz
  namespace: crdviz
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: crdviz
  type: ClusterIP