---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crdviz
resources:
- namespace.yaml
- service-account.yaml
- rbac.yaml
- deploy.yaml
- service.yaml
images:
- name: ghcr.io/dayzpd/crdviz
  newTag: "2"